// Package webadmin holds the admin UI's static assets: Go templates, one
// stylesheet, one script and the favicons (SPEC §4.4).
//
// The assets live in their own package because go:embed cannot reach outside
// the directory of the file that declares it, and internal/admin is not that
// directory. The package contains no logic on purpose — internal/admin owns
// every decision, this owns every byte.
//
// There is no second front-end build and no framework: the admin surface is
// one server-rendered screen (ROADMAP P4). The one script is hand-written,
// served from this origin, and does only what markup cannot — reveal a
// password field, copy a string, and show a creation code in a modal. Every
// page still works with scripting off, which is why the token listing carries
// a <noscript> fallback.
package webadmin

import "embed"

// FS holds the admin UI templates, stylesheet, script and favicons. The icons
// are generated by assets/icon/generate.py.
//
//go:embed *.html style.css app.js favicon.svg favicon.ico apple-touch-icon.png
var FS embed.FS
