// Clipboard entries: put, latest, history, fetch (SPEC §4.3, §6, ROADMAP P1).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tpp/v1/entry.proto

package tppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryMeta is everything the server knows about an entry. Note what is absent:
// content type, filename and plaintext size are inside the ciphertext and are
// never visible here (SPEC §2.3).
type EntryMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entry's identifier. It is the id the writing client chose and bound
	// into the ciphertext's associated data (see EntryPutRequest.entry_id), so a
	// reader can reproduce that binding before it decrypts.
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// The group epoch the entry was encrypted under. A client silently skips any
	// entry whose epoch is below its own (SPEC §3.3).
	Epoch uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Ciphertext length in bytes, as received by the server.
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Milliseconds since the Unix epoch, UTC.
	CreatedAtUnixMs int64 `protobuf:"varint,4,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	// created_at + 24h. Fixed at write time and never extended: the blob garbage
	// collector depends entirely on that (SPEC §4.5).
	ExpiresAtUnixMs int64 `protobuf:"varint,5,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	// True when the ciphertext is stored inline (<= 256 KB) and is therefore
	// delivered with the metadata; false when it lives in the blob backend and
	// must be pulled with EntryFetchRequest.
	Inline        bool `protobuf:"varint,6,opt,name=inline,proto3" json:"inline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryMeta) Reset() {
	*x = EntryMeta{}
	mi := &file_tpp_v1_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryMeta) ProtoMessage() {}

func (x *EntryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryMeta.ProtoReflect.Descriptor instead.
func (*EntryMeta) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{0}
}

func (x *EntryMeta) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *EntryMeta) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EntryMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EntryMeta) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *EntryMeta) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *EntryMeta) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

// EntryPutRequest uploads one encrypted clipboard item. The group and the
// author are taken from the connection's device identity.
type EntryPutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier chosen by the writing client, before it encrypts.
	//
	// /spec/crypto.md §5.3 binds the entry id into the ciphertext's associated
	// data, which only works if both sides know the id before decryption: a
	// server-assigned id would arrive in EntryPutResponse, after the ciphertext
	// was sealed, and the writer could never read back what it wrote. So the
	// client picks it, binds it, and sends it here; EntryPutResponse echoes it.
	//
	// The server treats it as opaque, but it is also the entry's key and its
	// blob filename (SPEC §4.2, §4.5), so it must match `[A-Za-z0-9_-]{1,64}` and
	// must not already exist. A client draws it from its CSPRNG with at least
	// 128 bits of entropy; a duplicate is refused with
	// ERROR_CODE_INVALID_ARGUMENT rather than overwriting anything.
	//
	// Empty means the server assigns one, for a client that binds no id. Such an
	// entry is written normally and its id is in the response.
	EntryId string `protobuf:"bytes,5,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// The epoch the ciphertext was encrypted under. The server rejects an epoch
	// that is not its current one.
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Ciphertext length in bytes, declared up front so the server can reject an
	// oversize entry before reading it. Must equal the actual body length;
	// anything above the 10 MB cap is refused with ERROR_CODE_TOO_LARGE
	// (SPEC §4.3).
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EntryPutRequest_Ciphertext
	//	*EntryPutRequest_UploadHandle
	Body          isEntryPutRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryPutRequest) Reset() {
	*x = EntryPutRequest{}
	mi := &file_tpp_v1_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryPutRequest) ProtoMessage() {}

func (x *EntryPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryPutRequest.ProtoReflect.Descriptor instead.
func (*EntryPutRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{1}
}

func (x *EntryPutRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *EntryPutRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EntryPutRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EntryPutRequest) GetBody() isEntryPutRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EntryPutRequest) GetCiphertext() []byte {
	if x != nil {
		if x, ok := x.Body.(*EntryPutRequest_Ciphertext); ok {
			return x.Ciphertext
		}
	}
	return nil
}

func (x *EntryPutRequest) GetUploadHandle() string {
	if x != nil {
		if x, ok := x.Body.(*EntryPutRequest_UploadHandle); ok {
			return x.UploadHandle
		}
	}
	return ""
}

type isEntryPutRequest_Body interface {
	isEntryPutRequest_Body()
}

type EntryPutRequest_Ciphertext struct {
	// Inline ciphertext, for entries up to 256 KB (SPEC §4.3).
	Ciphertext []byte `protobuf:"bytes,3,opt,name=ciphertext,proto3,oneof"`
}

type EntryPutRequest_UploadHandle struct {
	// Handle for ciphertext already streamed to the blob backend out of band.
	// Reserved for the large-entry upload path; how a handle is obtained is
	// ROADMAP P3c's to define. Clients that only send inline entries never set
	// this field.
	UploadHandle string `protobuf:"bytes,4,opt,name=upload_handle,json=uploadHandle,proto3,oneof"`
}

func (*EntryPutRequest_Ciphertext) isEntryPutRequest_Body() {}

func (*EntryPutRequest_UploadHandle) isEntryPutRequest_Body() {}

// EntryPutResponse confirms the write. The entry is the group's latest from
// this moment: last write to reach the server wins (SPEC §6).
type EntryPutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta.entry_id is the id from the request, echoed. A client that sent one
	// and gets a different id back must treat the entry as unreadable rather
	// than trusting it: the id it bound is not the id the entry now carries.
	Meta          *EntryMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryPutResponse) Reset() {
	*x = EntryPutResponse{}
	mi := &file_tpp_v1_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryPutResponse) ProtoMessage() {}

func (x *EntryPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryPutResponse.ProtoReflect.Descriptor instead.
func (*EntryPutResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{2}
}

func (x *EntryPutResponse) GetMeta() *EntryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EntryLatestRequest asks for the group's most recent entry. Sync operates on
// the latest entry only (SPEC §6).
type EntryLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryLatestRequest) Reset() {
	*x = EntryLatestRequest{}
	mi := &file_tpp_v1_entry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryLatestRequest) ProtoMessage() {}

func (x *EntryLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryLatestRequest.ProtoReflect.Descriptor instead.
func (*EntryLatestRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{3}
}

// EntryLatestResponse carries the latest entry, if there is one.
type EntryLatestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset when the group has no unexpired entry.
	Meta *EntryMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	// Present when meta.inline is true. Otherwise empty and the client issues an
	// EntryFetchRequest.
	Ciphertext    []byte `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryLatestResponse) Reset() {
	*x = EntryLatestResponse{}
	mi := &file_tpp_v1_entry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryLatestResponse) ProtoMessage() {}

func (x *EntryLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryLatestResponse.ProtoReflect.Descriptor instead.
func (*EntryLatestResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{4}
}

func (x *EntryLatestResponse) GetMeta() *EntryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *EntryLatestResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// EntryHistoryRequest lists entry metadata, newest first. History is only ever
// pulled: the server never pushes it, and a client must not fetch it on
// reconnect (SPEC §6).
type EntryHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of entries to return. Zero means the server's default.
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Cursor for paging: return only entries created strictly before this time,
	// in milliseconds since the Unix epoch, UTC. Zero means start at the newest.
	BeforeUnixMs  int64 `protobuf:"varint,2,opt,name=before_unix_ms,json=beforeUnixMs,proto3" json:"before_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryHistoryRequest) Reset() {
	*x = EntryHistoryRequest{}
	mi := &file_tpp_v1_entry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryHistoryRequest) ProtoMessage() {}

func (x *EntryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryHistoryRequest.ProtoReflect.Descriptor instead.
func (*EntryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{5}
}

func (x *EntryHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EntryHistoryRequest) GetBeforeUnixMs() int64 {
	if x != nil {
		return x.BeforeUnixMs
	}
	return 0
}

// EntryHistoryResponse returns metadata only. Bodies are pulled one at a time
// with EntryFetchRequest, when the user taps an entry to copy it.
type EntryHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest first.
	Entries []*EntryMeta `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Cursor to pass as the next request's before_unix_ms. Zero when the listing
	// reached the end.
	NextBeforeUnixMs int64 `protobuf:"varint,2,opt,name=next_before_unix_ms,json=nextBeforeUnixMs,proto3" json:"next_before_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EntryHistoryResponse) Reset() {
	*x = EntryHistoryResponse{}
	mi := &file_tpp_v1_entry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryHistoryResponse) ProtoMessage() {}

func (x *EntryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryHistoryResponse.ProtoReflect.Descriptor instead.
func (*EntryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{6}
}

func (x *EntryHistoryResponse) GetEntries() []*EntryMeta {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *EntryHistoryResponse) GetNextBeforeUnixMs() int64 {
	if x != nil {
		return x.NextBeforeUnixMs
	}
	return 0
}

// EntryFetchRequest pulls one entry's ciphertext by id.
type EntryFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryFetchRequest) Reset() {
	*x = EntryFetchRequest{}
	mi := &file_tpp_v1_entry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFetchRequest) ProtoMessage() {}

func (x *EntryFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFetchRequest.ProtoReflect.Descriptor instead.
func (*EntryFetchRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{7}
}

func (x *EntryFetchRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

// EntryFetchResponse returns the ciphertext, whether it was stored inline or in
// the blob backend; that distinction is the server's problem, not the client's.
type EntryFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EntryMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryFetchResponse) Reset() {
	*x = EntryFetchResponse{}
	mi := &file_tpp_v1_entry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFetchResponse) ProtoMessage() {}

func (x *EntryFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_entry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFetchResponse.ProtoReflect.Descriptor instead.
func (*EntryFetchResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_entry_proto_rawDescGZIP(), []int{8}
}

func (x *EntryFetchResponse) GetMeta() *EntryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *EntryFetchResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_tpp_v1_entry_proto protoreflect.FileDescriptor

const file_tpp_v1_entry_proto_rawDesc = "" +
	"\n" +
	"\x12tpp/v1/entry.proto\x12\x06tpp.v1\"\xc2\x01\n" +
	"\tEntryMeta\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12+\n" +
	"\x12created_at_unix_ms\x18\x04 \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12expires_at_unix_ms\x18\x05 \x01(\x03R\x0fexpiresAtUnixMs\x12\x16\n" +
	"\x06inline\x18\x06 \x01(\bR\x06inline\"\xa7\x01\n" +
	"\x0fEntryPutRequest\x12\x19\n" +
	"\bentry_id\x18\x05 \x01(\tR\aentryId\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12 \n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fH\x00R\n" +
	"ciphertext\x12%\n" +
	"\rupload_handle\x18\x04 \x01(\tH\x00R\fuploadHandleB\x06\n" +
	"\x04body\"9\n" +
	"\x10EntryPutResponse\x12%\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.tpp.v1.EntryMetaR\x04meta\"\x14\n" +
	"\x12EntryLatestRequest\"j\n" +
	"\x13EntryLatestResponse\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.tpp.v1.EntryMetaH\x00R\x04meta\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertextB\a\n" +
	"\x05_meta\"Q\n" +
	"\x13EntryHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12$\n" +
	"\x0ebefore_unix_ms\x18\x02 \x01(\x03R\fbeforeUnixMs\"r\n" +
	"\x14EntryHistoryResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.tpp.v1.EntryMetaR\aentries\x12-\n" +
	"\x13next_before_unix_ms\x18\x02 \x01(\x03R\x10nextBeforeUnixMs\".\n" +
	"\x11EntryFetchRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"[\n" +
	"\x12EntryFetchResponse\x12%\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.tpp.v1.EntryMetaR\x04meta\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertextBHZFgithub.com/Mark7888/two-place-paste/pkg/tppclient/protogen/tppv1;tppv1b\x06proto3"

var (
	file_tpp_v1_entry_proto_rawDescOnce sync.Once
	file_tpp_v1_entry_proto_rawDescData []byte
)

func file_tpp_v1_entry_proto_rawDescGZIP() []byte {
	file_tpp_v1_entry_proto_rawDescOnce.Do(func() {
		file_tpp_v1_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpp_v1_entry_proto_rawDesc), len(file_tpp_v1_entry_proto_rawDesc)))
	})
	return file_tpp_v1_entry_proto_rawDescData
}

var file_tpp_v1_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tpp_v1_entry_proto_goTypes = []any{
	(*EntryMeta)(nil),            // 0: tpp.v1.EntryMeta
	(*EntryPutRequest)(nil),      // 1: tpp.v1.EntryPutRequest
	(*EntryPutResponse)(nil),     // 2: tpp.v1.EntryPutResponse
	(*EntryLatestRequest)(nil),   // 3: tpp.v1.EntryLatestRequest
	(*EntryLatestResponse)(nil),  // 4: tpp.v1.EntryLatestResponse
	(*EntryHistoryRequest)(nil),  // 5: tpp.v1.EntryHistoryRequest
	(*EntryHistoryResponse)(nil), // 6: tpp.v1.EntryHistoryResponse
	(*EntryFetchRequest)(nil),    // 7: tpp.v1.EntryFetchRequest
	(*EntryFetchResponse)(nil),   // 8: tpp.v1.EntryFetchResponse
}
var file_tpp_v1_entry_proto_depIdxs = []int32{
	0, // 0: tpp.v1.EntryPutResponse.meta:type_name -> tpp.v1.EntryMeta
	0, // 1: tpp.v1.EntryLatestResponse.meta:type_name -> tpp.v1.EntryMeta
	0, // 2: tpp.v1.EntryHistoryResponse.entries:type_name -> tpp.v1.EntryMeta
	0, // 3: tpp.v1.EntryFetchResponse.meta:type_name -> tpp.v1.EntryMeta
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tpp_v1_entry_proto_init() }
func file_tpp_v1_entry_proto_init() {
	if File_tpp_v1_entry_proto != nil {
		return
	}
	file_tpp_v1_entry_proto_msgTypes[1].OneofWrappers = []any{
		(*EntryPutRequest_Ciphertext)(nil),
		(*EntryPutRequest_UploadHandle)(nil),
	}
	file_tpp_v1_entry_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpp_v1_entry_proto_rawDesc), len(file_tpp_v1_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tpp_v1_entry_proto_goTypes,
		DependencyIndexes: file_tpp_v1_entry_proto_depIdxs,
		MessageInfos:      file_tpp_v1_entry_proto_msgTypes,
	}.Build()
	File_tpp_v1_entry_proto = out.File
	file_tpp_v1_entry_proto_goTypes = nil
	file_tpp_v1_entry_proto_depIdxs = nil
}
