// TwoPlacePaste wire protocol, version 1 (SPEC §5.1, ROADMAP P1).
//
// Every frame on the WebSocket is a serialized Envelope. Nothing else is ever
// written to the socket. The concrete message travels as opaque bytes in
// `payload`, which is what makes the transport replaceable at zero cost: a
// future HTTP/2 or gRPC carrier moves Envelopes without any message in this
// package changing.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tpp/v1/envelope.proto

package tppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType names every message that may appear in Envelope.payload.
//
// Numbers are permanent: they are the on-the-wire contract between clients that
// upgrade independently. Never renumber, never reuse a removed number.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// Errors.
	MessageType_MESSAGE_TYPE_ERROR MessageType = 1
	// Group creation (SPEC §3.1).
	MessageType_MESSAGE_TYPE_CREATE_GROUP_REQUEST  MessageType = 10
	MessageType_MESSAGE_TYPE_CREATE_GROUP_RESPONSE MessageType = 11
	// Pairing (SPEC §3.2).
	MessageType_MESSAGE_TYPE_PAIRING_START_REQUEST      MessageType = 20
	MessageType_MESSAGE_TYPE_PAIRING_START_RESPONSE     MessageType = 21
	MessageType_MESSAGE_TYPE_PAIRING_JOIN_REQUEST       MessageType = 22
	MessageType_MESSAGE_TYPE_PAIRING_JOIN_NOTICE        MessageType = 23
	MessageType_MESSAGE_TYPE_PAIRING_WRAPPED_KEY_UPLOAD MessageType = 24
	MessageType_MESSAGE_TYPE_PAIRING_COMPLETE           MessageType = 25
	// Joiner-emitted pairing: the same exchange with the roles swapped, so that
	// the device without a group key can be the one that shows a code
	// (docs/plans/joiner-emitted-pairing.md). PairingComplete above is reused
	// unchanged as the last step of both directions.
	MessageType_MESSAGE_TYPE_PAIRING_OFFER_REQUEST        MessageType = 26
	MessageType_MESSAGE_TYPE_PAIRING_OFFER_RESPONSE       MessageType = 27
	MessageType_MESSAGE_TYPE_PAIRING_OFFER_ACCEPT_REQUEST MessageType = 28
	// Devices and rekey (SPEC §3.3).
	MessageType_MESSAGE_TYPE_DEVICE_LIST_REQUEST  MessageType = 30
	MessageType_MESSAGE_TYPE_DEVICE_LIST_RESPONSE MessageType = 31
	MessageType_MESSAGE_TYPE_REKEY_REQUEST        MessageType = 32
	MessageType_MESSAGE_TYPE_REKEY_RESPONSE       MessageType = 33
	// Entries (SPEC §4.3, §6).
	MessageType_MESSAGE_TYPE_ENTRY_PUT_REQUEST      MessageType = 40
	MessageType_MESSAGE_TYPE_ENTRY_PUT_RESPONSE     MessageType = 41
	MessageType_MESSAGE_TYPE_ENTRY_LATEST_REQUEST   MessageType = 42
	MessageType_MESSAGE_TYPE_ENTRY_LATEST_RESPONSE  MessageType = 43
	MessageType_MESSAGE_TYPE_ENTRY_HISTORY_REQUEST  MessageType = 44
	MessageType_MESSAGE_TYPE_ENTRY_HISTORY_RESPONSE MessageType = 45
	MessageType_MESSAGE_TYPE_ENTRY_FETCH_REQUEST    MessageType = 46
	MessageType_MESSAGE_TYPE_ENTRY_FETCH_RESPONSE   MessageType = 47
	// Server-pushed events. These are never requested and never answered.
	MessageType_MESSAGE_TYPE_EPOCH_CHANGED         MessageType = 50
	MessageType_MESSAGE_TYPE_WRAPPED_KEY_AVAILABLE MessageType = 51
	MessageType_MESSAGE_TYPE_DEVICE_REVOKED        MessageType = 52
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_ERROR",
		10: "MESSAGE_TYPE_CREATE_GROUP_REQUEST",
		11: "MESSAGE_TYPE_CREATE_GROUP_RESPONSE",
		20: "MESSAGE_TYPE_PAIRING_START_REQUEST",
		21: "MESSAGE_TYPE_PAIRING_START_RESPONSE",
		22: "MESSAGE_TYPE_PAIRING_JOIN_REQUEST",
		23: "MESSAGE_TYPE_PAIRING_JOIN_NOTICE",
		24: "MESSAGE_TYPE_PAIRING_WRAPPED_KEY_UPLOAD",
		25: "MESSAGE_TYPE_PAIRING_COMPLETE",
		26: "MESSAGE_TYPE_PAIRING_OFFER_REQUEST",
		27: "MESSAGE_TYPE_PAIRING_OFFER_RESPONSE",
		28: "MESSAGE_TYPE_PAIRING_OFFER_ACCEPT_REQUEST",
		30: "MESSAGE_TYPE_DEVICE_LIST_REQUEST",
		31: "MESSAGE_TYPE_DEVICE_LIST_RESPONSE",
		32: "MESSAGE_TYPE_REKEY_REQUEST",
		33: "MESSAGE_TYPE_REKEY_RESPONSE",
		40: "MESSAGE_TYPE_ENTRY_PUT_REQUEST",
		41: "MESSAGE_TYPE_ENTRY_PUT_RESPONSE",
		42: "MESSAGE_TYPE_ENTRY_LATEST_REQUEST",
		43: "MESSAGE_TYPE_ENTRY_LATEST_RESPONSE",
		44: "MESSAGE_TYPE_ENTRY_HISTORY_REQUEST",
		45: "MESSAGE_TYPE_ENTRY_HISTORY_RESPONSE",
		46: "MESSAGE_TYPE_ENTRY_FETCH_REQUEST",
		47: "MESSAGE_TYPE_ENTRY_FETCH_RESPONSE",
		50: "MESSAGE_TYPE_EPOCH_CHANGED",
		51: "MESSAGE_TYPE_WRAPPED_KEY_AVAILABLE",
		52: "MESSAGE_TYPE_DEVICE_REVOKED",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":                  0,
		"MESSAGE_TYPE_ERROR":                        1,
		"MESSAGE_TYPE_CREATE_GROUP_REQUEST":         10,
		"MESSAGE_TYPE_CREATE_GROUP_RESPONSE":        11,
		"MESSAGE_TYPE_PAIRING_START_REQUEST":        20,
		"MESSAGE_TYPE_PAIRING_START_RESPONSE":       21,
		"MESSAGE_TYPE_PAIRING_JOIN_REQUEST":         22,
		"MESSAGE_TYPE_PAIRING_JOIN_NOTICE":          23,
		"MESSAGE_TYPE_PAIRING_WRAPPED_KEY_UPLOAD":   24,
		"MESSAGE_TYPE_PAIRING_COMPLETE":             25,
		"MESSAGE_TYPE_PAIRING_OFFER_REQUEST":        26,
		"MESSAGE_TYPE_PAIRING_OFFER_RESPONSE":       27,
		"MESSAGE_TYPE_PAIRING_OFFER_ACCEPT_REQUEST": 28,
		"MESSAGE_TYPE_DEVICE_LIST_REQUEST":          30,
		"MESSAGE_TYPE_DEVICE_LIST_RESPONSE":         31,
		"MESSAGE_TYPE_REKEY_REQUEST":                32,
		"MESSAGE_TYPE_REKEY_RESPONSE":               33,
		"MESSAGE_TYPE_ENTRY_PUT_REQUEST":            40,
		"MESSAGE_TYPE_ENTRY_PUT_RESPONSE":           41,
		"MESSAGE_TYPE_ENTRY_LATEST_REQUEST":         42,
		"MESSAGE_TYPE_ENTRY_LATEST_RESPONSE":        43,
		"MESSAGE_TYPE_ENTRY_HISTORY_REQUEST":        44,
		"MESSAGE_TYPE_ENTRY_HISTORY_RESPONSE":       45,
		"MESSAGE_TYPE_ENTRY_FETCH_REQUEST":          46,
		"MESSAGE_TYPE_ENTRY_FETCH_RESPONSE":         47,
		"MESSAGE_TYPE_EPOCH_CHANGED":                50,
		"MESSAGE_TYPE_WRAPPED_KEY_AVAILABLE":        51,
		"MESSAGE_TYPE_DEVICE_REVOKED":               52,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_tpp_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_tpp_v1_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_tpp_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope is the single frame type of the protocol.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation id, chosen by the sender of a request and echoed verbatim on
	// the matching response or Error. Server-pushed events carry a fresh id that
	// correlates with nothing.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Discriminator for `payload`. A receiver that does not know the type
	// answers with ERROR_CODE_UNSUPPORTED_MESSAGE rather than closing the socket.
	Type MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=tpp.v1.MessageType" json:"type,omitempty"`
	// The serialized message named by `type`. Empty for message types whose body
	// has no fields.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_tpp_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_tpp_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_tpp_v1_envelope_proto protoreflect.FileDescriptor

const file_tpp_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x15tpp/v1/envelope.proto\x12\x06tpp.v1\"]\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.tpp.v1.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*\xad\b\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x01\x12%\n" +
	"!MESSAGE_TYPE_CREATE_GROUP_REQUEST\x10\n" +
	"\x12&\n" +
	"\"MESSAGE_TYPE_CREATE_GROUP_RESPONSE\x10\v\x12&\n" +
	"\"MESSAGE_TYPE_PAIRING_START_REQUEST\x10\x14\x12'\n" +
	"#MESSAGE_TYPE_PAIRING_START_RESPONSE\x10\x15\x12%\n" +
	"!MESSAGE_TYPE_PAIRING_JOIN_REQUEST\x10\x16\x12$\n" +
	" MESSAGE_TYPE_PAIRING_JOIN_NOTICE\x10\x17\x12+\n" +
	"'MESSAGE_TYPE_PAIRING_WRAPPED_KEY_UPLOAD\x10\x18\x12!\n" +
	"\x1dMESSAGE_TYPE_PAIRING_COMPLETE\x10\x19\x12&\n" +
	"\"MESSAGE_TYPE_PAIRING_OFFER_REQUEST\x10\x1a\x12'\n" +
	"#MESSAGE_TYPE_PAIRING_OFFER_RESPONSE\x10\x1b\x12-\n" +
	")MESSAGE_TYPE_PAIRING_OFFER_ACCEPT_REQUEST\x10\x1c\x12$\n" +
	" MESSAGE_TYPE_DEVICE_LIST_REQUEST\x10\x1e\x12%\n" +
	"!MESSAGE_TYPE_DEVICE_LIST_RESPONSE\x10\x1f\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_REKEY_REQUEST\x10 \x12\x1f\n" +
	"\x1bMESSAGE_TYPE_REKEY_RESPONSE\x10!\x12\"\n" +
	"\x1eMESSAGE_TYPE_ENTRY_PUT_REQUEST\x10(\x12#\n" +
	"\x1fMESSAGE_TYPE_ENTRY_PUT_RESPONSE\x10)\x12%\n" +
	"!MESSAGE_TYPE_ENTRY_LATEST_REQUEST\x10*\x12&\n" +
	"\"MESSAGE_TYPE_ENTRY_LATEST_RESPONSE\x10+\x12&\n" +
	"\"MESSAGE_TYPE_ENTRY_HISTORY_REQUEST\x10,\x12'\n" +
	"#MESSAGE_TYPE_ENTRY_HISTORY_RESPONSE\x10-\x12$\n" +
	" MESSAGE_TYPE_ENTRY_FETCH_REQUEST\x10.\x12%\n" +
	"!MESSAGE_TYPE_ENTRY_FETCH_RESPONSE\x10/\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_EPOCH_CHANGED\x102\x12&\n" +
	"\"MESSAGE_TYPE_WRAPPED_KEY_AVAILABLE\x103\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_DEVICE_REVOKED\x104BHZFgithub.com/Mark7888/two-place-paste/pkg/tppclient/protogen/tppv1;tppv1b\x06proto3"

var (
	file_tpp_v1_envelope_proto_rawDescOnce sync.Once
	file_tpp_v1_envelope_proto_rawDescData []byte
)

func file_tpp_v1_envelope_proto_rawDescGZIP() []byte {
	file_tpp_v1_envelope_proto_rawDescOnce.Do(func() {
		file_tpp_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpp_v1_envelope_proto_rawDesc), len(file_tpp_v1_envelope_proto_rawDesc)))
	})
	return file_tpp_v1_envelope_proto_rawDescData
}

var file_tpp_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tpp_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tpp_v1_envelope_proto_goTypes = []any{
	(MessageType)(0), // 0: tpp.v1.MessageType
	(*Envelope)(nil), // 1: tpp.v1.Envelope
}
var file_tpp_v1_envelope_proto_depIdxs = []int32{
	0, // 0: tpp.v1.Envelope.type:type_name -> tpp.v1.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tpp_v1_envelope_proto_init() }
func file_tpp_v1_envelope_proto_init() {
	if File_tpp_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpp_v1_envelope_proto_rawDesc), len(file_tpp_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tpp_v1_envelope_proto_goTypes,
		DependencyIndexes: file_tpp_v1_envelope_proto_depIdxs,
		EnumInfos:         file_tpp_v1_envelope_proto_enumTypes,
		MessageInfos:      file_tpp_v1_envelope_proto_msgTypes,
	}.Build()
	File_tpp_v1_envelope_proto = out.File
	file_tpp_v1_envelope_proto_goTypes = nil
	file_tpp_v1_envelope_proto_depIdxs = nil
}
