// Protocol errors (SPEC §5.1, ROADMAP P1).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tpp/v1/error.proto

package tppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is the stable enum every client branches on.
//
// Numbers are permanent. A code is never removed and never given new meaning;
// a new condition gets a new number.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// The frame or its payload could not be decoded, or a field is out of range.
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 1
	// The connection has not established a device identity, or the identity was
	// invalidated by a revocation (SPEC §3.3 step 5).
	ErrorCode_ERROR_CODE_UNAUTHENTICATED ErrorCode = 2
	// The device is authenticated but is not a member of the target group.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 3
	// No such group, device, entry, or pairing.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 4
	// The creation token has already produced a group. One token, one group,
	// no reuse (SPEC §3.1).
	ErrorCode_ERROR_CODE_TOKEN_CONSUMED ErrorCode = 5
	// The pairing token has passed its short lifetime (SPEC §3.2).
	ErrorCode_ERROR_CODE_TOKEN_EXPIRED ErrorCode = 6
	// RekeyRequest.expected_epoch does not match the group's current epoch:
	// another device rekeyed first. The caller refetches the roster and retries
	// (SPEC §3.3 step 4).
	ErrorCode_ERROR_CODE_EPOCH_CONFLICT ErrorCode = 7
	// The ciphertext exceeds the 10 MB per-entry cap (SPEC §4.3).
	ErrorCode_ERROR_CODE_TOO_LARGE ErrorCode = 8
	// Rate limited. The caller backs off and retries.
	ErrorCode_ERROR_CODE_RATE_LIMITED ErrorCode = 9
	// Envelope.type is unknown to this peer, or is not legal in this direction.
	ErrorCode_ERROR_CODE_UNSUPPORTED_MESSAGE ErrorCode = 10
	// Server-side failure. The caller may retry; nothing about the cause is
	// disclosed beyond this code.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 11
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_ARGUMENT",
		2:  "ERROR_CODE_UNAUTHENTICATED",
		3:  "ERROR_CODE_PERMISSION_DENIED",
		4:  "ERROR_CODE_NOT_FOUND",
		5:  "ERROR_CODE_TOKEN_CONSUMED",
		6:  "ERROR_CODE_TOKEN_EXPIRED",
		7:  "ERROR_CODE_EPOCH_CONFLICT",
		8:  "ERROR_CODE_TOO_LARGE",
		9:  "ERROR_CODE_RATE_LIMITED",
		10: "ERROR_CODE_UNSUPPORTED_MESSAGE",
		11: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_INVALID_ARGUMENT":    1,
		"ERROR_CODE_UNAUTHENTICATED":     2,
		"ERROR_CODE_PERMISSION_DENIED":   3,
		"ERROR_CODE_NOT_FOUND":           4,
		"ERROR_CODE_TOKEN_CONSUMED":      5,
		"ERROR_CODE_TOKEN_EXPIRED":       6,
		"ERROR_CODE_EPOCH_CONFLICT":      7,
		"ERROR_CODE_TOO_LARGE":           8,
		"ERROR_CODE_RATE_LIMITED":        9,
		"ERROR_CODE_UNSUPPORTED_MESSAGE": 10,
		"ERROR_CODE_INTERNAL":            11,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_tpp_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_tpp_v1_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_tpp_v1_error_proto_rawDescGZIP(), []int{0}
}

// Error is the response to any request that could not be served. It is sent in
// an Envelope whose id echoes the failed request.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable, machine-readable cause. Clients branch on this, never on `message`.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=tpp.v1.ErrorCode" json:"code,omitempty"`
	// Human-readable detail for logs and operator-facing UI.
	//
	// This string reaches server logs, so it obeys docs/conventions.md §1: it may
	// name an entry id, an epoch, a device id or a byte length, and it may never
	// contain ciphertext, a key, a wrapped key, a creation token, a pairing
	// token, a filename or a content type (SPEC §2.3).
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_tpp_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_tpp_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tpp_v1_error_proto protoreflect.FileDescriptor

const file_tpp_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x12tpp/v1/error.proto\x12\x06tpp.v1\"H\n" +
	"\x05Error\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.tpp.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xf4\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_TOKEN_CONSUMED\x10\x05\x12\x1c\n" +
	"\x18ERROR_CODE_TOKEN_EXPIRED\x10\x06\x12\x1d\n" +
	"\x19ERROR_CODE_EPOCH_CONFLICT\x10\a\x12\x18\n" +
	"\x14ERROR_CODE_TOO_LARGE\x10\b\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\t\x12\"\n" +
	"\x1eERROR_CODE_UNSUPPORTED_MESSAGE\x10\n" +
	"\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\vBHZFgithub.com/Mark7888/two-place-paste/pkg/tppclient/protogen/tppv1;tppv1b\x06proto3"

var (
	file_tpp_v1_error_proto_rawDescOnce sync.Once
	file_tpp_v1_error_proto_rawDescData []byte
)

func file_tpp_v1_error_proto_rawDescGZIP() []byte {
	file_tpp_v1_error_proto_rawDescOnce.Do(func() {
		file_tpp_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpp_v1_error_proto_rawDesc), len(file_tpp_v1_error_proto_rawDesc)))
	})
	return file_tpp_v1_error_proto_rawDescData
}

var file_tpp_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tpp_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tpp_v1_error_proto_goTypes = []any{
	(ErrorCode)(0), // 0: tpp.v1.ErrorCode
	(*Error)(nil),  // 1: tpp.v1.Error
}
var file_tpp_v1_error_proto_depIdxs = []int32{
	0, // 0: tpp.v1.Error.code:type_name -> tpp.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tpp_v1_error_proto_init() }
func file_tpp_v1_error_proto_init() {
	if File_tpp_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpp_v1_error_proto_rawDesc), len(file_tpp_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tpp_v1_error_proto_goTypes,
		DependencyIndexes: file_tpp_v1_error_proto_depIdxs,
		EnumInfos:         file_tpp_v1_error_proto_enumTypes,
		MessageInfos:      file_tpp_v1_error_proto_msgTypes,
	}.Build()
	File_tpp_v1_error_proto = out.File
	file_tpp_v1_error_proto_goTypes = nil
	file_tpp_v1_error_proto_depIdxs = nil
}
