// Server-pushed events (SPEC §3.2, §3.3, ROADMAP P1).
//
// Events are unsolicited: they are never requested and are never answered. A
// client that receives one it does not understand ignores it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tpp/v1/events.proto

package tppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EpochChanged tells every remaining device that the group has been re-keyed
// (SPEC §3.3). Entries below the new epoch are skipped from here on; they are
// not deleted and expire naturally within 24 hours.
//
// Receiving this must never touch the OS clipboard.
type EpochChanged struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The device whose revocation caused the rekey.
	RevokedDeviceId string `protobuf:"bytes,2,opt,name=revoked_device_id,json=revokedDeviceId,proto3" json:"revoked_device_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EpochChanged) Reset() {
	*x = EpochChanged{}
	mi := &file_tpp_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochChanged) ProtoMessage() {}

func (x *EpochChanged) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochChanged.ProtoReflect.Descriptor instead.
func (*EpochChanged) Descriptor() ([]byte, []int) {
	return file_tpp_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EpochChanged) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochChanged) GetRevokedDeviceId() string {
	if x != nil {
		return x.RevokedDeviceId
	}
	return ""
}

// WrappedKeyAvailable delivers this device's copy of the new group key. It is
// pushed on connect if the device was offline during the rekey: a wrapped key
// waits for a device rather than requiring it to be online (SPEC §3.3).
type WrappedKeyAvailable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The new group key wrapped to the receiving device's public key.
	WrappedGroupKey []byte `protobuf:"bytes,2,opt,name=wrapped_group_key,json=wrappedGroupKey,proto3" json:"wrapped_group_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WrappedKeyAvailable) Reset() {
	*x = WrappedKeyAvailable{}
	mi := &file_tpp_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedKeyAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedKeyAvailable) ProtoMessage() {}

func (x *WrappedKeyAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedKeyAvailable.ProtoReflect.Descriptor instead.
func (*WrappedKeyAvailable) Descriptor() ([]byte, []int) {
	return file_tpp_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *WrappedKeyAvailable) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *WrappedKeyAvailable) GetWrappedGroupKey() []byte {
	if x != nil {
		return x.WrappedGroupKey
	}
	return nil
}

// DeviceRevoked tells the group that a device is gone, so a roster on screen
// can update without refetching. The revoked device's own socket is closed in
// the same operation rather than being told (SPEC §3.3 step 5).
type DeviceRevoked struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// The epoch the group runs at after the revocation.
	Epoch         uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRevoked) Reset() {
	*x = DeviceRevoked{}
	mi := &file_tpp_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRevoked) ProtoMessage() {}

func (x *DeviceRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRevoked.ProtoReflect.Descriptor instead.
func (*DeviceRevoked) Descriptor() ([]byte, []int) {
	return file_tpp_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceRevoked) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRevoked) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// EntryAdded tells the rest of the group that a new entry is the latest. It is
// sent to every other connected device of the group, never to the author.
//
// It carries metadata only: a client that wants the content fetches it, and
// only when its user has opted into applying remote entries to the local
// clipboard (SPEC §6). A client that has not opted in ignores it.
type EntryAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *EntryMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryAdded) Reset() {
	*x = EntryAdded{}
	mi := &file_tpp_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryAdded) ProtoMessage() {}

func (x *EntryAdded) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryAdded.ProtoReflect.Descriptor instead.
func (*EntryAdded) Descriptor() ([]byte, []int) {
	return file_tpp_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *EntryAdded) GetMeta() *EntryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_tpp_v1_events_proto protoreflect.FileDescriptor

const file_tpp_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x13tpp/v1/events.proto\x12\x06tpp.v1\x1a\x12tpp/v1/entry.proto\"P\n" +
	"\fEpochChanged\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12*\n" +
	"\x11revoked_device_id\x18\x02 \x01(\tR\x0frevokedDeviceId\"W\n" +
	"\x13WrappedKeyAvailable\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12*\n" +
	"\x11wrapped_group_key\x18\x02 \x01(\fR\x0fwrappedGroupKey\"B\n" +
	"\rDeviceRevoked\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\"3\n" +
	"\n" +
	"EntryAdded\x12%\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.tpp.v1.EntryMetaR\x04metaBHZFgithub.com/Mark7888/two-place-paste/pkg/tppclient/protogen/tppv1;tppv1b\x06proto3"

var (
	file_tpp_v1_events_proto_rawDescOnce sync.Once
	file_tpp_v1_events_proto_rawDescData []byte
)

func file_tpp_v1_events_proto_rawDescGZIP() []byte {
	file_tpp_v1_events_proto_rawDescOnce.Do(func() {
		file_tpp_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpp_v1_events_proto_rawDesc), len(file_tpp_v1_events_proto_rawDesc)))
	})
	return file_tpp_v1_events_proto_rawDescData
}

var file_tpp_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tpp_v1_events_proto_goTypes = []any{
	(*EpochChanged)(nil),        // 0: tpp.v1.EpochChanged
	(*WrappedKeyAvailable)(nil), // 1: tpp.v1.WrappedKeyAvailable
	(*DeviceRevoked)(nil),       // 2: tpp.v1.DeviceRevoked
	(*EntryAdded)(nil),          // 3: tpp.v1.EntryAdded
	(*EntryMeta)(nil),           // 4: tpp.v1.EntryMeta
}
var file_tpp_v1_events_proto_depIdxs = []int32{
	4, // 0: tpp.v1.EntryAdded.meta:type_name -> tpp.v1.EntryMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tpp_v1_events_proto_init() }
func file_tpp_v1_events_proto_init() {
	if File_tpp_v1_events_proto != nil {
		return
	}
	file_tpp_v1_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpp_v1_events_proto_rawDesc), len(file_tpp_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tpp_v1_events_proto_goTypes,
		DependencyIndexes: file_tpp_v1_events_proto_depIdxs,
		MessageInfos:      file_tpp_v1_events_proto_msgTypes,
	}.Build()
	File_tpp_v1_events_proto = out.File
	file_tpp_v1_events_proto_goTypes = nil
	file_tpp_v1_events_proto_depIdxs = nil
}
