// Group creation, device roster and rekey (SPEC §3.1, §3.3, ROADMAP P1).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tpp/v1/group.proto

package tppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateGroupRequest turns a one-time creation token into a group (SPEC §3.1
// step 4). The client has already generated its device keypair and a fresh
// group key, and has wrapped that group key to its own public key: the server
// only ever receives the wrapped form.
//
// This is one of the two frames an unauthenticated connection may send; the
// other is PairingJoinRequest.
type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token from https://<host>/<token>. Consumed by this request and by no
	// other; a GET of that URL returns 404 (SPEC §3.1).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Raw device public key. Algorithm and byte layout are pinned by
	// /spec/crypto.md (ROADMAP P2), not here.
	DevicePublicKey []byte `protobuf:"bytes,2,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	// The group key wrapped to device_public_key. Opaque to the server.
	WrappedGroupKey []byte `protobuf:"bytes,3,opt,name=wrapped_group_key,json=wrappedGroupKey,proto3" json:"wrapped_group_key,omitempty"`
	// Human-chosen device name, shown in the revocation confirmation dialog
	// (SPEC §3.3 step 2). Not a secret, but not clipboard content either.
	DeviceName    string `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_tpp_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateGroupRequest) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *CreateGroupRequest) GetWrappedGroupKey() []byte {
	if x != nil {
		return x.WrappedGroupKey
	}
	return nil
}

func (x *CreateGroupRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// CreateGroupResponse reports the identifiers the client stores for the life of
// the installation.
type CreateGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The consumed token is the group identifier (SPEC §3.1 step 5).
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Server-assigned identifier for the creating device.
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Always 1 for a freshly created group; stated explicitly so a client never
	// has to assume a starting epoch.
	Epoch         uint64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_tpp_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateGroupResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// Device is one member of a group, as the server knows it (SPEC §4.2).
type Device struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Name supplied at creation or pairing time.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The device's public key, used by a rekeying peer to wrap the new group key
	// (SPEC §3.3 step 3).
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Milliseconds since the Unix epoch, UTC (docs/conventions.md §6).
	CreatedAtUnixMs int64 `protobuf:"varint,4,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	// Milliseconds since the Unix epoch, UTC. Zero when the device has never
	// connected.
	LastSeenUnixMs int64 `protobuf:"varint,5,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_tpp_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Device) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Device) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

// DeviceListRequest asks for the current roster. It carries no fields: the
// group is determined by the connection's device identity.
type DeviceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceListRequest) Reset() {
	*x = DeviceListRequest{}
	mi := &file_tpp_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceListRequest) ProtoMessage() {}

func (x *DeviceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceListRequest.ProtoReflect.Descriptor instead.
func (*DeviceListRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{3}
}

// DeviceListResponse is the roster a client must render, by name, before it may
// offer to revoke anything (SPEC §3.3 steps 1-2).
type DeviceListResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Devices []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	// The group's current epoch, to be echoed as RekeyRequest.expected_epoch.
	Epoch         uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceListResponse) Reset() {
	*x = DeviceListResponse{}
	mi := &file_tpp_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceListResponse) ProtoMessage() {}

func (x *DeviceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceListResponse.ProtoReflect.Descriptor instead.
func (*DeviceListResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceListResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *DeviceListResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// WrappedKey carries the new group key encrypted to one device's public key.
type WrappedKey struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Opaque to the server. Layout pinned by /spec/crypto.md (ROADMAP P2).
	WrappedGroupKey []byte `protobuf:"bytes,2,opt,name=wrapped_group_key,json=wrappedGroupKey,proto3" json:"wrapped_group_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WrappedKey) Reset() {
	*x = WrappedKey{}
	mi := &file_tpp_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedKey) ProtoMessage() {}

func (x *WrappedKey) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedKey.ProtoReflect.Descriptor instead.
func (*WrappedKey) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *WrappedKey) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *WrappedKey) GetWrappedGroupKey() []byte {
	if x != nil {
		return x.WrappedGroupKey
	}
	return nil
}

// RekeyRequest revokes one device and re-keys every remaining one in a single
// frame (SPEC §3.3 step 4).
//
// The server applies the whole request atomically: every wrapped key is
// written, the revoked device is deleted, and the epoch is incremented, or
// nothing happens at all. A client that dies mid-upload leaves the group
// untouched at the old epoch. Splitting this into several requests would break
// that guarantee, which is why the wrapped keys are a repeated field rather
// than a stream.
type RekeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The device being removed. It must not appear in wrapped_keys.
	RevokedDeviceId string `protobuf:"bytes,1,opt,name=revoked_device_id,json=revokedDeviceId,proto3" json:"revoked_device_id,omitempty"`
	// The epoch the caller believes is current, from DeviceListResponse.epoch.
	// A mismatch means another device rekeyed first; the server rejects the
	// request with ERROR_CODE_EPOCH_CONFLICT and changes nothing.
	ExpectedEpoch uint64 `protobuf:"varint,2,opt,name=expected_epoch,json=expectedEpoch,proto3" json:"expected_epoch,omitempty"`
	// Exactly one entry per remaining device, including the caller itself.
	WrappedKeys   []*WrappedKey `protobuf:"bytes,3,rep,name=wrapped_keys,json=wrappedKeys,proto3" json:"wrapped_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RekeyRequest) Reset() {
	*x = RekeyRequest{}
	mi := &file_tpp_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyRequest) ProtoMessage() {}

func (x *RekeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyRequest.ProtoReflect.Descriptor instead.
func (*RekeyRequest) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{6}
}

func (x *RekeyRequest) GetRevokedDeviceId() string {
	if x != nil {
		return x.RevokedDeviceId
	}
	return ""
}

func (x *RekeyRequest) GetExpectedEpoch() uint64 {
	if x != nil {
		return x.ExpectedEpoch
	}
	return 0
}

func (x *RekeyRequest) GetWrappedKeys() []*WrappedKey {
	if x != nil {
		return x.WrappedKeys
	}
	return nil
}

// RekeyResponse reports the epoch the group now runs at.
type RekeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expected_epoch + 1.
	Epoch         uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RekeyResponse) Reset() {
	*x = RekeyResponse{}
	mi := &file_tpp_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyResponse) ProtoMessage() {}

func (x *RekeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpp_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyResponse.ProtoReflect.Descriptor instead.
func (*RekeyResponse) Descriptor() ([]byte, []int) {
	return file_tpp_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *RekeyResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_tpp_v1_group_proto protoreflect.FileDescriptor

const file_tpp_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x12tpp/v1/group.proto\x12\x06tpp.v1\"\xa3\x01\n" +
	"\x12CreateGroupRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12*\n" +
	"\x11device_public_key\x18\x02 \x01(\fR\x0fdevicePublicKey\x12*\n" +
	"\x11wrapped_group_key\x18\x03 \x01(\fR\x0fwrappedGroupKey\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\"c\n" +
	"\x13CreateGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\"\xb0\x01\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12+\n" +
	"\x12created_at_unix_ms\x18\x04 \x01(\x03R\x0fcreatedAtUnixMs\x12)\n" +
	"\x11last_seen_unix_ms\x18\x05 \x01(\x03R\x0elastSeenUnixMs\"\x13\n" +
	"\x11DeviceListRequest\"T\n" +
	"\x12DeviceListResponse\x12(\n" +
	"\adevices\x18\x01 \x03(\v2\x0e.tpp.v1.DeviceR\adevices\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\"U\n" +
	"\n" +
	"WrappedKey\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12*\n" +
	"\x11wrapped_group_key\x18\x02 \x01(\fR\x0fwrappedGroupKey\"\x98\x01\n" +
	"\fRekeyRequest\x12*\n" +
	"\x11revoked_device_id\x18\x01 \x01(\tR\x0frevokedDeviceId\x12%\n" +
	"\x0eexpected_epoch\x18\x02 \x01(\x04R\rexpectedEpoch\x125\n" +
	"\fwrapped_keys\x18\x03 \x03(\v2\x12.tpp.v1.WrappedKeyR\vwrappedKeys\"%\n" +
	"\rRekeyResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epochBHZFgithub.com/Mark7888/two-place-paste/pkg/tppclient/protogen/tppv1;tppv1b\x06proto3"

var (
	file_tpp_v1_group_proto_rawDescOnce sync.Once
	file_tpp_v1_group_proto_rawDescData []byte
)

func file_tpp_v1_group_proto_rawDescGZIP() []byte {
	file_tpp_v1_group_proto_rawDescOnce.Do(func() {
		file_tpp_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpp_v1_group_proto_rawDesc), len(file_tpp_v1_group_proto_rawDesc)))
	})
	return file_tpp_v1_group_proto_rawDescData
}

var file_tpp_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tpp_v1_group_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),  // 0: tpp.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil), // 1: tpp.v1.CreateGroupResponse
	(*Device)(nil),              // 2: tpp.v1.Device
	(*DeviceListRequest)(nil),   // 3: tpp.v1.DeviceListRequest
	(*DeviceListResponse)(nil),  // 4: tpp.v1.DeviceListResponse
	(*WrappedKey)(nil),          // 5: tpp.v1.WrappedKey
	(*RekeyRequest)(nil),        // 6: tpp.v1.RekeyRequest
	(*RekeyResponse)(nil),       // 7: tpp.v1.RekeyResponse
}
var file_tpp_v1_group_proto_depIdxs = []int32{
	2, // 0: tpp.v1.DeviceListResponse.devices:type_name -> tpp.v1.Device
	5, // 1: tpp.v1.RekeyRequest.wrapped_keys:type_name -> tpp.v1.WrappedKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tpp_v1_group_proto_init() }
func file_tpp_v1_group_proto_init() {
	if File_tpp_v1_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpp_v1_group_proto_rawDesc), len(file_tpp_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tpp_v1_group_proto_goTypes,
		DependencyIndexes: file_tpp_v1_group_proto_depIdxs,
		MessageInfos:      file_tpp_v1_group_proto_msgTypes,
	}.Build()
	File_tpp_v1_group_proto = out.File
	file_tpp_v1_group_proto_goTypes = nil
	file_tpp_v1_group_proto_depIdxs = nil
}
